/**
 * Next.js Pages Router 全局入口：每个页面渲染前都会经过本组件。
 *
 * Provider 从外到内：Theme → Wagmi → React Query → RainbowKit → Layout → 当前页
 * 原理：React Context 向内传递；子组件用的 hook 必须在对应 Provider 子树内。
 */
import '../styles/globals.css'; // Tailwind 与全局样式入口
import '@rainbow-me/rainbowkit/styles.css'; // 连接钱包按钮默认样式
import type { AppProps } from 'next/app'; // Component=当前页, pageProps=getServerSideProps 等传入的 props
import { ThemeProvider } from '@mui/material/styles';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'; // wagmi v2 依赖其缓存 RPC
import { WagmiProvider } from 'wagmi';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { config } from '../utils/wagmi'; // 链、transport、projectId
import theme from '../utils/theme';
import { ToastContainer } from 'react-toastify'; // 全局 toast 挂载点
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head'; // 修改 document <title> 等
import Layout from '../components/Layout'; // 顶栏 + 主内容区 + 页脚

/** 全应用共用一个 QueryClient，避免重复创建导致缓存丢失 */
const client = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      {/* Head 内容会注入到 HTML <head> */}
      <Head>
        <title>Meta Node Stake</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      {/* MUI 主题：子树内 MUI 组件可读 palette */}
      <ThemeProvider theme={theme}>
        {/* wagmi：useAccount、useBalance、useConnectorClient 等必须在其内部 */}
        <WagmiProvider config={config}>
          {/* 必须在 WagmiProvider 内；wagmi 内部用 TanStack Query 管理请求 */}
          <QueryClientProvider client={client}>
            {/* RainbowKit：ConnectButton 依赖 wagmi 上下文 */}
            <RainbowKitProvider locale="en-US">
              {/* 任意子组件 toast.success/error 都会显示在这里 */}
              <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
                toastClassName="custom-toast"
              />
              {/* Layout 的 children = 当前路由页面（index / withdraw / claim） */}
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </RainbowKitProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
