/**
 * Next.js Pages Router 的全局应用入口（对应 App Router 里的 root layout）。
 *
 * 为什么需要 _app.tsx？
 * - 每个具体页面（index、withdraw、claim）只负责自己的 UI；公共的「包一层 Provider、统一布局、全局样式」都放在这里。
 * - Next.js 会把当前路由对应的页面组件作为 Component 传进来，见下方 <Component {...pageProps} />。
 *
 * Provider 嵌套顺序（从外到内）与原理：
 * 1. ThemeProvider（MUI）
 *    - 若页面里用到 @mui/material 组件，它们会消费这份 theme（颜色、字体等）。
 * 2. WagmiProvider
 *    - 注入 wagmi 的 config（链、RPC transport 等）。所有 useAccount、useWalletClient、useBalance 必须在它的子树里。
 * 3. QueryClientProvider
 *    - wagmi v2 内部用 TanStack Query 做请求缓存与去重；必须与 WagmiProvider 搭配使用（顺序按官方示例：在 Wagmi 内层）。
 * 4. RainbowKitProvider
 *    - 连接钱包 UI（ConnectButton）依赖 wagmi 上下文，因此要放在 WagmiProvider 内部。
 *
 * 读完本文件后，建议接着看：pages/index.tsx → components/Layout.tsx → utils/wagmi.ts
 */
import '../styles/globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import type { AppProps } from 'next/app';
import { ThemeProvider } from '@mui/material/styles';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { WagmiProvider } from 'wagmi';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { config } from '../utils/wagmi';
import theme from '../utils/theme';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import Layout from '../components/Layout';

/** 整个应用共用一个 QueryClient，避免重复创建导致缓存失效 */
const client = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Meta Node Stake</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      {/*MUI组件库*/}
      <ThemeProvider theme={theme}>
        <WagmiProvider config={config}>
          <QueryClientProvider client={client}>
            <RainbowKitProvider locale="en-US">
              {/*
                ToastContainer：全局挂载一次即可，任意子组件里调用 toast.success/error 都会显示。
                仅保留类型支持的 props（react-toastify v11 部分 className 子项已变更）。
                就是一个全局消息通知系统：
              */}
              <ToastContainer
                  position="top-right"        // 📍 显示位置：右上角
                  autoClose={3000}            // ⏰ 自动关闭：3秒后消失
                  hideProgressBar={false}     // 📊 显示进度条（倒计时）
                  newestOnTop={false}         // 📋 新消息不在最上面
                  closeOnClick                // 👆 点击可以关闭
                  rtl={false}                 // ➡️ 不从右到左排列
                  pauseOnFocusLoss            // ⏸️ 失去焦点时暂停
                  draggable                   // 🖱️ 可以拖动关闭
                  pauseOnHover                // ⏸️ 鼠标悬停时暂停计时
                  theme="light"               // 🎨 浅色主题
                  toastClassName="custom-toast" // 🎭 自定义样式类名
              />
              {/*
                Layout 提供顶栏、页脚、背景；children 区域渲染当前路由页面。
              */}
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </RainbowKitProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
